export const cuisineList = [
    "Ugali",
    "Mukimo",
    "Pilau",
    "Githeri",
    "Matoke",
    "Biryani",
    "Samosas",
    "Beef stew",
    "Bhajias",
    "Mutura",
    "Chips mayai",
    "Coconut rice",
    "Wali wa nazi",
    "Kenyan stew",
    "Sukuma wiki",
    "Nyama choma",
    "Maharagwe",
    "Kachumbari",
    "Njahi",
    "IRIO",
    "Mandazi",
    "Nduma",
    "Kuku Paka",
    "Coleslaw",
    "Pork",
    "Chicken",
];